tl_core_homepage:
    path:     /
    defaults: { _controller: TLCoreBundle:Core:index }

tl_core_informations:
    path:     /informations
    defaults: { _controller: TLCoreBundle:Core:informations }
