tl_core_homepage:
    path:     /
    defaults: { _controller: TLCoreBundle:Core:index }

tl_core_informations:
    path:     /informations
    defaults: { _controller: TLCoreBundle:Core:informations }

tl_core_summary:
    path:     /summary
    defaults: { _controller: TLCoreBundle:Core:summary }
