services:
    tl_core.validator.hours:
        class: TL\CoreBundle\Validator\HoursValidator
        arguments: ["@request_stack"]
        tags:
            - { name: validator.constraint_validator, alias: tl_core_hours }

    tl_core.validator.closed:
        class: TL\CoreBundle\Validator\ClosedValidator
        arguments: ["@request_stack"]
        tags:
            - { name: validator.constraint_validator, alias: tl_core_closed }

    tl_core.validator.day:
        class: TL\CoreBundle\Validator\DayValidator
        arguments: ["@request_stack"]
        tags:
            - { name: validator.constraint_validator, alias: tl_core_day }

    tl_core.validator.limit:
        class: TL\CoreBundle\Validator\LimitValidator
        arguments: ["@request_stack", "@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: tl_core_limit }

    tl_core.services.calculator:
        class: TL\CoreBundle\Services\Calculator

    tl_core.services.email:
        class: TL\CoreBundle\Services\Email\TicketsMailer
        arguments:
            - "@mailer"
            - "@templating"

    tl_core.doctrine_listener.command_validation:
        class: TL\CoreBundle\DoctrineListener\CommandValidationListener
        arguments:
            - "@tl_core.services.email"
        tags:
            - { name: doctrine.event_listener, event: postPersist }

