services:
    tl_core.validator.hours:
        class: TL\CoreBundle\Validator\HoursValidator
        arguments: ["@request_stack", "@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: tl_core_hours }

    tl_core.services.calculator:
        class: TL\CoreBundle\Services\Calculator
